/*
DROP TABLE IF EXISTS USPTO.PATENT_INTERNATIONAL_CLASSIFICATION;
DROP TABLE IF EXISTS USPTO.PATENT_US_CLASSIFICATION;
DROP TABLE IF EXISTS USPTO.PATENT_PEOPLE;
DROP TABLE IF EXISTS USPTO.PATENT_REFERENCE;
DROP TABLE IF EXISTS USPTO.OTHER_REFERENCE;
DROP TABLE IF EXISTS USPTO.US_CLASSIFICATION;
DROP TABLE IF EXISTS USPTO.INTERNATIONAL_CLASSIFICATION;
DROP TABLE IF EXISTS USPTO.PERSON;
DROP TABLE IF EXISTS USPTO.CLAIM;
DROP TABLE IF EXISTS USPTO.PATENT;
DROP TABLE IF EXISTS USPTO.FILE;
*/

CREATE TABLE `FILE`
(
    `ID`               INT(9)       NOT NULL AUTO_INCREMENT,
    `NAME`             VARCHAR(255) NOT NULL UNIQUE,
    `URL`              VARCHAR(255) NOT NULL UNIQUE,
    `PUBLICATION_DATE` DATE         NOT NULL UNIQUE,
    `DOWNLOAD_DATE`    DATETIME     NOT NULL,
    `PROCESS_DATE`     DATETIME,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `PATENT`
(
    `DOCUMENT_NUMBER`  VARCHAR(15)  NOT NULL,
    `FILE_ID`          INT(15) UNIQUE,
    `PUBLICATION_DATE` DATE         NOT NULL,
    `TITLE`             VARCHAR(255) NOT NULL,
    `FILE_NAME`        VARCHAR(255) NOT NULL,
    `ABSTRACT`         MEDIUMTEXT  NOT NULL,
    PRIMARY KEY (`DOCUMENT_NUMBER`)
);

CREATE TABLE `PERSON`
(
    `ID`                INT(9)     NOT NULL AUTO_INCREMENT,
    `TYPE`              VARCHAR(9) NOT NULL,
    `FIRST_NAME`        VARCHAR(50),
    `LAST_NAME`         VARCHAR(50),
    `ORGANIZATION_NAME` VARCHAR(80),
    `COUNTRY`           VARCHAR(20) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `PATENT_PEOPLE`
(
    `PATENT_DOCUMENT_NUMBER` VARCHAR(15) NOT NULL,
    `PERSON_ID` INT(9)      NOT NULL,
    PRIMARY KEY (`PATENT_DOCUMENT_NUMBER`, `PERSON_ID`)
);

CREATE TABLE `CLAIM`
(
    `ID`        INT(15)     NOT NULL AUTO_INCREMENT,
    `PATENT_DOCUMENT_NUMBER` VARCHAR(15) NOT NULL,
    `CLAIM`     MEDIUMTEXT  NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `INTERNATIONAL_CLASSIFICATION`
(
    `ID`                INT(9)     NOT NULL AUTO_INCREMENT,
    `TYPE`              VARCHAR(9) NOT NULL,
    `VERSION_INDICATOR` VARCHAR(10),
    `SECTION`           VARCHAR(10),
    `CLASS_NAME`        VARCHAR(10),
    `SUB_CLASS`         VARCHAR(10),
    `MAIN_GROUP`        VARCHAR(10),
    `SUB_GROUP`         VARCHAR(10),
    PRIMARY KEY (`ID`)
);

CREATE TABLE `US_CLASSIFICATION`
(
    `ID`                INT(9)     NOT NULL AUTO_INCREMENT,
    `CLASS`             VARCHAR(3),
    `SUB_CLASS`         VARCHAR(10),
    PRIMARY KEY (`ID`)
);

CREATE TABLE `PATENT_US_CLASSIFICATION`
(
    `PATENT_DOCUMENT_NUMBER`         VARCHAR(15) NOT NULL,
    `US_CLASSIFICATION_ID` INT(9)      NOT NULL,
    PRIMARY KEY (`PATENT_DOCUMENT_NUMBER`, `US_CLASSIFICATION_ID`)
);


CREATE TABLE `PATENT_INTERNATIONAL_CLASSIFICATION`
(
    `PATENT_DOCUMENT_NUMBER`         VARCHAR(15) NOT NULL,
    `INTERNATIONAL_CLASSIFICATION_ID` INT(9)      NOT NULL,
    PRIMARY KEY (`PATENT_DOCUMENT_NUMBER`, `INTERNATIONAL_CLASSIFICATION_ID`)
);

CREATE TABLE `PATENT_REFERENCE`
(
    `ID`               INT(15)     NOT NULL AUTO_INCREMENT,
    `PATENT_DOCUMENT_NUMBER`        VARCHAR(15) NOT NULL,
    `REFERENCE_DOCUMENT_NUMBER`       VARCHAR(20) NOT NULL,
    `PUBLICATION_DATE` DATE        NOT NULL,
    `KIND`             VARCHAR(5),
    `COUNTRY`          VARCHAR(5),
    `TITLE`             VARCHAR(255),
    PRIMARY KEY (`ID`)
);

CREATE TABLE `OTHER_REFERENCE`
(
    `ID`          INT(15)      NOT NULL AUTO_INCREMENT,
    `PATENT_DOCUMENT_NUMBER`   VARCHAR(15)  NOT NULL,
    `DESCRIPTION` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);


ALTER TABLE `PATENT`
    ADD CONSTRAINT `PATENT_FK0` FOREIGN KEY (`FILE_ID`) REFERENCES `FILE` (`ID`);

ALTER TABLE `PATENT_PEOPLE`
    ADD CONSTRAINT `PATENTS_PEOPLE_FK0` FOREIGN KEY (`PATENT_DOCUMENT_NUMBER`) REFERENCES `PATENT` (`DOCUMENT_NUMBER`);

ALTER TABLE `PATENT_PEOPLE`
    ADD CONSTRAINT `PATENTS_PEOPLE_FK1` FOREIGN KEY (`PERSON_ID`) REFERENCES `PERSON` (`ID`);

ALTER TABLE `CLAIM`
    ADD CONSTRAINT `CLAIM_FK0` FOREIGN KEY (`PATENT_DOCUMENT_NUMBER`) REFERENCES `PATENT` (`DOCUMENT_NUMBER`);

ALTER TABLE PATENT_US_CLASSIFICATION
    ADD CONSTRAINT `PATENT_US_CLASSIFICATION_FK0` FOREIGN KEY (`PATENT_DOCUMENT_NUMBER`) REFERENCES `PATENT` (`DOCUMENT_NUMBER`);

ALTER TABLE PATENT_US_CLASSIFICATION
    ADD CONSTRAINT `PATENT_US_CLASSIFICATION_FK1` FOREIGN KEY (`US_CLASSIFICATION_ID`) REFERENCES `US_CLASSIFICATION` (`ID`);

ALTER TABLE PATENT_INTERNATIONAL_CLASSIFICATION
    ADD CONSTRAINT `PATENTS_INTERNATIONAL_CLASSIFICATION_FK0` FOREIGN KEY (`PATENT_DOCUMENT_NUMBER`) REFERENCES `PATENT` (`DOCUMENT_NUMBER`);

ALTER TABLE PATENT_INTERNATIONAL_CLASSIFICATION
    ADD CONSTRAINT `PATENTS_INTERNATIONAL_CLASSIFICATION_FK1` FOREIGN KEY (`INTERNATIONAL_CLASSIFICATION_ID`) REFERENCES `INTERNATIONAL_CLASSIFICATION` (`ID`);

ALTER TABLE `PATENT_REFERENCE`
    ADD CONSTRAINT `PATENT_REFERENCE_FK0` FOREIGN KEY (`PATENT_DOCUMENT_NUMBER`) REFERENCES `PATENT` (`DOCUMENT_NUMBER`);

ALTER TABLE `OTHER_REFERENCE`
    ADD CONSTRAINT `OTHER_REFERENCE_FK0` FOREIGN KEY (`PATENT_DOCUMENT_NUMBER`) REFERENCES `PATENT` (`DOCUMENT_NUMBER`);

ALTER TABLE `FILE`
    ADD CONSTRAINT UNIQUE (NAME, URL, PUBLICATION_DATE);

ALTER TABLE `PERSON`
    ADD CONSTRAINT UNIQUE (TYPE, FIRST_NAME, LAST_NAME, ORGANIZATION_NAME, COUNTRY);

ALTER TABLE `INTERNATIONAL_CLASSIFICATION`
    ADD CONSTRAINT UNIQUE (VERSION_INDICATOR, TYPE, SECTION, CLASS_NAME, SUB_CLASS, MAIN_GROUP, SUB_GROUP);

ALTER TABLE `US_CLASSIFICATION`
    ADD CONSTRAINT UNIQUE (CLASS, SUB_CLASS);

ALTER TABLE `PATENT_REFERENCE`
    ADD CONSTRAINT UNIQUE (PATENT_DOCUMENT_NUMBER, REFERENCE_DOCUMENT_NUMBER);
